version: '3'

services:
  app:
    build: ./eltrello-client/Dockerfile
    ports: 
      - '4200:4200'
    depends_on:
      - api
    networks:
      - trello-network
  
  api:
    build: /server/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - trello-network
  
  mongodb:
    image: mongo:latest
    container_name: mongodatabase
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
    networks:
      - trello-network

networks:
  trello-network: