version: '3'

services:

  # Frontend
  app:
    build: 
      context: .
      dockerfile: ./eltrello-client/Dockerfile # with this setting, files will be reference with absolute path
    ports: 
      - '4200:80'
    environment:
      - BASE_URL=http://api:3000/api
    depends_on:
      - api
    networks:
      - trello-network
  
  # API
  api:
    build: ./server/ # with this setting, files will be reference with relative path
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ELASTIC_URL=http://elasticsearch:9200
      - MONGODB_URL=mongodb://mongodb:27017/eltrello
    depends_on:
      - mongodb
    networks:
      - trello-network
  
  # Mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodatabase
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
    networks:
      - trello-network

  # Elasticserch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    volumes:
      - trello-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      #- xpack.monitoring.enabled=true
      # - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - "discovery.type=single-node"
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - target: 9200
        published: 9200
    networks:
      - trello-network
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    # image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - target: 5601
        published: 5601
    networks:
      - trello-network

volumes:
  trello-elasticsearch-data:

networks:
  trello-network:
    driver: bridge